import { Injectable } from '@nestjs/common';
import { AsyncLocalStorage } from 'node:async_hooks';

/**
 * Propagates the HTTP `requestId` across async call chains within a single request
 * using Node.js `AsyncLocalStorage` — no extra packages required.
 *
 * Stored as a `@Global()` singleton via `TraceModule`; the same `AsyncLocalStorage`
 * instance is shared by every module, so reads always reflect the current request context.
 */
@Injectable()
export class TraceContextService {
  private readonly store = new AsyncLocalStorage<string>();

  /**
   * Runs `fn` with `id` stored as the current context's request identifier.
   *
   * Call this in `RequestIdMiddleware` at the start of each HTTP request.
   *
   * @param id - The UUID v7 request identifier generated by `genReqId` in pino-http.
   * @param fn - The continuation to execute within this context.
   */
  run(id: string, fn: () => void): void {
    this.store.run(id, fn);
  }

  /**
   * Returns the request ID for the current async context, or `undefined` when called
   * outside an HTTP request (e.g. cron schedulers, worker boot).
   */
  getRequestId(): string | undefined {
    return this.store.getStore();
  }
}
