import { Migration } from '@mikro-orm/migrations';

/**
 * Creates the `billing.billing_events` table.
 *
 * `stripe_event_id` has a UNIQUE constraint (BR-R04) — this is the idempotency key
 * that prevents duplicate Stripe webhook deliveries from being processed twice.
 *
 * `id` is a UUID v7 generated by the application; no DB DEFAULT (ADR-013).
 * Append-only — no `updated_at` column (messaging infra exception per CLAUDE.md §3).
 */
export class Migration20260703000002_BillingEvents extends Migration {
  override async up(): Promise<void> {
    this.addSql(`
      CREATE TABLE billing.billing_events (
        id               UUID          PRIMARY KEY,
        stripe_event_id  VARCHAR(255)  NOT NULL,
        event_type       VARCHAR(100)  NOT NULL,
        event_payload    JSONB         NOT NULL,
        occurred_at      TIMESTAMPTZ   NOT NULL,
        subscription_id  UUID          REFERENCES billing.subscriptions (id) ON DELETE RESTRICT,
        created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
        CONSTRAINT uq_billing_events_stripe_event_id UNIQUE (stripe_event_id)
      );
    `);

    this.addSql(`CREATE INDEX idx_billing_events_subscription_id ON billing.billing_events (subscription_id);`);
    this.addSql(`CREATE INDEX idx_billing_events_occurred_at ON billing.billing_events (occurred_at);`);
  }

  override async down(): Promise<void> {
    this.addSql(`DROP TABLE IF EXISTS billing.billing_events;`);
  }
}
