import { Filter, PrimaryKey, Property } from '@mikro-orm/decorators/legacy';
import type { Opt } from '@mikro-orm/core';
import { uuidv7 } from 'uuidv7';

/**
 * Abstract base class for every MikroORM entity in the platform.
 *
 * Provides:
 * - A UUID v7 primary key generated by the application before persistence (no DB DEFAULT).
 * - `createdAt` / `updatedAt` / `deletedAt` timestamp triplet (BR-R04).
 * - A default `softDelete` filter that hides rows where `deletedAt` is not null.
 *
 * All entities must extend this class. Never add `@PrimaryKey` to a subclass.
 * To soft-delete, set `entity.deletedAt = new Date()` and call `em.flush()`.
 * Hard purges are only performed by scheduled retention jobs, never in-request.
 */
@Filter({ name: 'softDelete', cond: { deletedAt: null }, default: true })
export abstract class BaseEntity {
  /** Application-generated time-ordered UUID v7 primary key (ADR-013). */
  @PrimaryKey({ type: 'uuid' })
  id: string = uuidv7();

  /** Timestamp set once when the row is first inserted. */
  @Property({ type: 'timestamptz', defaultRaw: 'now()' })
  createdAt: Date & Opt = new Date();

  /** Timestamp updated automatically by MikroORM on every flush that modifies the entity. */
  @Property({ type: 'timestamptz', defaultRaw: 'now()', onUpdate: () => new Date() })
  updatedAt: Date & Opt = new Date();

  /**
   * Soft-delete marker. When set to a non-null value the row is excluded from all
   * queries by the default `softDelete` filter. Null means the entity is active.
   */
  @Property({ type: 'timestamptz', nullable: true })
  deletedAt?: Date;
}
