import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';

/**
 * Request body for `POST /workspaces/:workspaceId/facebook/pages`.
 *
 * The client receives `code` and `state` from Facebook's OAuth redirect and
 * forwards them to this endpoint. The backend verifies the state HMAC and
 * exchanges the code for page access tokens.
 */
export class ConnectPageDto {
  /**
   * OAuth authorization code issued by Facebook after the user grants permission.
   * Single-use; expires after a short period (~10 minutes).
   */
  @ApiProperty({ description: 'OAuth authorization code from the Facebook redirect' })
  @IsString()
  @IsNotEmpty()
  code!: string;

  /**
   * CSRF state token originally generated by `GET /facebook/connect-url`.
   * Format: `base64url(payload).<hmac-sha256-hex>`.
   * The backend re-verifies the HMAC and the embedded `workspaceId` (BR-R05).
   */
  @ApiProperty({ description: 'CSRF state token from the Facebook redirect (must match the value from connect-url)' })
  @IsString()
  @IsNotEmpty()
  state!: string;
}

/**
 * A single connected Facebook Page returned from `POST /workspaces/:workspaceId/facebook/pages`.
 *
 * BR-F11: the access token is **never** included in this response.
 */
export class ConnectedPageResponseDto {
  /** UUID v7 of the `core.facebook_accounts` record. */
  @ApiProperty()
  id!: string;

  /** Facebook Page ID (external identifier from the Graph API). */
  @ApiProperty()
  pageId!: string;

  /** Display name of the Facebook Page. */
  @ApiProperty()
  pageName!: string;

  /** When the Page was first connected (or re-connected) to the workspace. */
  @ApiProperty()
  connectedAt!: Date;
}
