import type { Post } from '../entities/post.entity';
import type { CreatePostData } from '../entities/post.entity';

/**
 * Opaque keyset cursor payload encoded as base64url JSON.
 * Used to continue a `findAll` page from the last seen row.
 */
export interface ListPostsCursor {
  /** ISO-8601 `createdAt` of the last row on the previous page. */
  createdAt: string;
  /** UUID v7 `id` of the last row — breaks ties within the same millisecond. */
  id: string;
}

/**
 * Query options for the paginated `findAll` method.
 *
 * Defaults: `limit = 50`, no cursor (returns the first page).
 * Maximum `limit` is capped at 100 by the adapter.
 */
export interface ListPostsQuery {
  /** Maximum number of posts to return. Default 50; adapter caps at 100. */
  limit?: number;
  /** base64url-encoded `ListPostsCursor` from the previous page response. */
  cursor?: string;
}

/**
 * Result of a paginated `findAll` call.
 *
 * `nextCursor` is `null` when there are no more pages.
 * Pass it back as `?cursor=<value>` on the next request to get the next page.
 */
export interface PostsPage {
  /** Posts for this page, ordered `createdAt DESC, id DESC`. */
  data: Post[];
  /** Opaque cursor for the next page, or `null` on the last page. */
  nextCursor: string | null;
}

/**
 * Port (outbound): persistence contract for `Post` aggregates.
 *
 * All ORM details (`em.getReference`, `persist`, `flush`) are encapsulated in the
 * adapter. Services depend on this abstract class only (§14).
 */
export abstract class IPostRepository {
  /**
   * Finds a post by its primary key, scoped to a specific workspace.
   *
   * Returns `null` if the post does not exist, is soft-deleted, or belongs to a
   * different workspace — without exposing cross-workspace data.
   *
   * @param id          - UUID v7 of the post.
   * @param workspaceId - UUID of the owning workspace.
   */
  abstract findById(id: string, workspaceId: string): Promise<Post | null>;

  /**
   * Returns a page of active (non-deleted) posts for a workspace, ordered by
   * `createdAt DESC, id DESC` (keyset pagination — §12).
   *
   * Pass `query.cursor` from the previous response's `nextCursor` to advance pages.
   * Default page size is 50; adapter caps at 100.
   *
   * @param workspaceId - UUID of the owning workspace.
   * @param query       - Pagination options (limit, cursor).
   */
  abstract findAll(workspaceId: string, query?: ListPostsQuery): Promise<PostsPage>;

  /**
   * Counts non-deleted posts for a workspace. Used to enforce plan quota (PLAN_LIMIT_EXCEEDED).
   *
   * @param workspaceId - UUID of the owning workspace.
   */
  abstract countByWorkspace(workspaceId: string): Promise<number>;

  /**
   * Checks whether a `FacebookAccount` belongs to the given workspace.
   *
   * Used to enforce BR-R05 before creating a post with a `facebookAccountId`.
   * The adapter imports the `FacebookAccount` entity class directly (§13 — cross-module
   * entity access via EntityManager to avoid NestJS circular module dependencies).
   *
   * @param accountId   - UUID v7 of the `FacebookAccount` to validate.
   * @param workspaceId - UUID of the workspace that must own the account.
   * @returns `true` if the account exists and belongs to the workspace.
   */
  abstract facebookAccountBelongsToWorkspace(
    accountId: string,
    workspaceId: string,
  ): Promise<boolean>;

  /**
   * Creates a new `Post` entity, persists it, and flushes the Unit of Work.
   *
   * The adapter calls `em.getReference(Workspace, workspaceId)` and (if provided)
   * `em.getReference(FacebookAccount, facebookAccountId)` to avoid unnecessary SELECTs.
   * A UUID v7 is generated by `Post.create()` before persistence (no DB DEFAULT).
   *
   * @param workspaceId       - UUID of the owning workspace.
   * @param facebookAccountId - UUID of the target Page connection, or `null`.
   * @param createdByUserId   - UUID of the creating user (logical FK — BR-R06).
   * @param data              - Post fields.
   * @returns The newly persisted `Post`.
   */
  abstract createPost(
    workspaceId: string,
    facebookAccountId: string | null,
    createdByUserId: string,
    data: CreatePostData,
  ): Promise<Post>;

  /**
   * Flushes pending changes to an already-tracked `Post` entity.
   *
   * Call after modifying entity properties (update, soft-delete). The entity must
   * already be in the current MikroORM Unit of Work (i.e., loaded via `findById`
   * in the same request context).
   *
   * @param post - The managed entity whose changes should be flushed.
   */
  abstract save(post: Post): Promise<void>;

  /**
   * Soft-deletes all non-terminal posts for a workspace **without flushing**.
   *
   * "Non-terminal" means status is `draft`, `scheduled`, or `publishing`; posts
   * already in `published` or `failed` state are left untouched (they are immutable
   * historical records).
   *
   * The entities are loaded into the current Unit of Work and marked dirty
   * (`deletedAt = now()`). The caller is responsible for calling `em.flush()` to
   * commit the changes atomically together with other cascade mutations (W-1, §6).
   *
   * Returns the count rather than the full entity list: callers only need the count
   * for the `WorkspaceDeletedEvent` payload — emitting one event per cancelled post
   * would produce N events for N posts (W-1 Fix 2).
   *
   * @param workspaceId - UUID of the workspace being deleted.
   * @returns Number of non-terminal posts that were soft-deleted.
   */
  abstract softDeleteNonTerminalByWorkspace(workspaceId: string): Promise<number>;
}
