import type { Post } from '../entities/post.entity';
import type { CreatePostData } from '../entities/post.entity';

/**
 * Port (outbound): persistence contract for `Post` aggregates.
 *
 * All ORM details (`em.getReference`, `persist`, `flush`) are encapsulated in the
 * adapter. Services depend on this abstract class only (§14).
 */
export abstract class IPostRepository {
  /**
   * Finds a post by its primary key, scoped to a specific workspace.
   *
   * Returns `null` if the post does not exist, is soft-deleted, or belongs to a
   * different workspace — without exposing cross-workspace data.
   *
   * @param id          - UUID v7 of the post.
   * @param workspaceId - UUID of the owning workspace.
   */
  abstract findById(id: string, workspaceId: string): Promise<Post | null>;

  /**
   * Returns all active (non-deleted) posts for a workspace, ordered by
   * `createdAt` descending.
   *
   * @param workspaceId - UUID of the owning workspace.
   */
  abstract findAll(workspaceId: string): Promise<Post[]>;

  /**
   * Counts non-deleted posts for a workspace. Used to enforce plan quota (PLAN_LIMIT_EXCEEDED).
   *
   * @param workspaceId - UUID of the owning workspace.
   */
  abstract countByWorkspace(workspaceId: string): Promise<number>;

  /**
   * Checks whether a `FacebookAccount` belongs to the given workspace.
   *
   * Used to enforce BR-R05 before creating a post with a `facebookAccountId`.
   * The adapter imports the `FacebookAccount` entity class directly (§13 — cross-module
   * entity access via EntityManager to avoid NestJS circular module dependencies).
   *
   * @param accountId   - UUID v7 of the `FacebookAccount` to validate.
   * @param workspaceId - UUID of the workspace that must own the account.
   * @returns `true` if the account exists and belongs to the workspace.
   */
  abstract facebookAccountBelongsToWorkspace(
    accountId: string,
    workspaceId: string,
  ): Promise<boolean>;

  /**
   * Creates a new `Post` entity, persists it, and flushes the Unit of Work.
   *
   * The adapter calls `em.getReference(Workspace, workspaceId)` and (if provided)
   * `em.getReference(FacebookAccount, facebookAccountId)` to avoid unnecessary SELECTs.
   * A UUID v7 is generated by `Post.create()` before persistence (no DB DEFAULT).
   *
   * @param workspaceId       - UUID of the owning workspace.
   * @param facebookAccountId - UUID of the target Page connection, or `null`.
   * @param createdByUserId   - UUID of the creating user (logical FK — BR-R06).
   * @param data              - Post fields.
   * @returns The newly persisted `Post`.
   */
  abstract createPost(
    workspaceId: string,
    facebookAccountId: string | null,
    createdByUserId: string,
    data: CreatePostData,
  ): Promise<Post>;

  /**
   * Flushes pending changes to an already-tracked `Post` entity.
   *
   * Call after modifying entity properties (update, soft-delete). The entity must
   * already be in the current MikroORM Unit of Work (i.e., loaded via `findById`
   * in the same request context).
   *
   * @param post - The managed entity whose changes should be flushed.
   */
  abstract save(post: Post): Promise<void>;
}
